#!/usr/bin/env node
/**
 * First-run setup after cloning PigeonBox.
 *   npm run setup            install, create local dev config, build, verify the manifest
 *   npm run setup -- --open  also open the built folder and chrome://extensions
 *
 * Needs no PigeonBox account, Cloud backend, Supabase, Stripe, Convex,
 * Cloudflare account or AI key.
 */
import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateManifest } from './lib/extension-package.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const openAfter = process.argv.includes('--open');
const PLACEHOLDER_TOKEN = 'generate-a-long-random-token';

function fail(message) {
  console.error(`\n${message}\n`);
  process.exit(1);
}

function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: root,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });
  if (result.error) fail(`${command} could not be started: ${result.error.message}`);
  return result.status ?? 1;
}

function parseEnv(text) {
  const values = {};
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    values[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return values;
}

function isReal(value, placeholders) {
  if (!value) return false;
  return !placeholders.some((placeholder) => value.includes(placeholder));
}

const nodeMajor = Number(process.versions.node.split('.')[0]);
if (!Number.isFinite(nodeMajor) || nodeMajor < 20) {
  fail(
    `This project needs Node.js 20 or newer. You have ${process.version}.\n` +
      'Install the current LTS from https://nodejs.org and run this again.',
  );
}

if (!existsSync(join(root, 'node_modules', 'typescript'))) {
  console.log('\nInstalling dependencies (first time only)…\n');
  const status = existsSync(join(root, 'package-lock.json'))
    ? run('npm', ['ci'])
    : run('npm', ['install']);
  if (status !== 0) fail('Dependency install failed. Fix the error above, then run npm run setup again.');
}

const envPath = join(root, '.env');
const examplePath = join(root, '.env.example');
if (!existsSync(envPath)) {
  if (!existsSync(examplePath)) fail('Missing .env.example');
  writeFileSync(envPath, readFileSync(examplePath, 'utf8'));
  console.log('Created .env from .env.example');
}

let envText = readFileSync(envPath, 'utf8');
let env = parseEnv(envText);
const devVarsPath = join(root, 'workers', 'tracker', '.dev.vars');
const existingDev = existsSync(devVarsPath) ? parseEnv(readFileSync(devVarsPath, 'utf8')) : null;

if (!isReal(env.PERSONAL_API_TOKEN, [PLACEHOLDER_TOKEN])) {
  const token = isReal(existingDev?.PERSONAL_API_TOKEN, [PLACEHOLDER_TOKEN])
    ? existingDev.PERSONAL_API_TOKEN
    : randomBytes(32).toString('base64url');
  if (envText.includes(`PERSONAL_API_TOKEN=${PLACEHOLDER_TOKEN}`)) {
    envText = envText.replace(`PERSONAL_API_TOKEN=${PLACEHOLDER_TOKEN}`, `PERSONAL_API_TOKEN=${token}`);
  } else if (envText.includes('PERSONAL_API_TOKEN=')) {
    envText = envText.replace(/PERSONAL_API_TOKEN=.*/g, `PERSONAL_API_TOKEN=${token}`);
  } else {
    envText += `\nPERSONAL_API_TOKEN=${token}\n`;
  }
  writeFileSync(envPath, envText);
  env = parseEnv(envText);
  console.log(
    existingDev?.PERSONAL_API_TOKEN === token
      ? 'Copied the existing tracker token into .env'
      : 'Generated a personal API token in .env',
  );
}

if (!existsSync(devVarsPath)) {
  const supabaseUrl = isReal(env.SUPABASE_URL, ['YOUR_PROJECT']) ? env.SUPABASE_URL : '';
  const supabaseKey = isReal(env.SUPABASE_SERVICE_ROLE_KEY, ['your-service-role-key'])
    ? env.SUPABASE_SERVICE_ROLE_KEY
    : '';
  const lines = [
    '# Generated by npm run setup. This file is gitignored.',
    `PERSONAL_API_TOKEN=${env.PERSONAL_API_TOKEN}`,
    '',
    '# Leave Supabase unset to store tracking events in memory.',
    '# They disappear when you stop `npm run tracker`.',
  ];
  lines.push(supabaseUrl ? `SUPABASE_URL=${supabaseUrl}` : '# SUPABASE_URL=');
  lines.push(supabaseKey ? `SUPABASE_SERVICE_ROLE_KEY=${supabaseKey}` : '# SUPABASE_SERVICE_ROLE_KEY=');
  lines.push('');
  writeFileSync(devVarsPath, lines.join('\n'));
  console.log('Created workers/tracker/.dev.vars for the local tracker');
}

const devVars = parseEnv(readFileSync(devVarsPath, 'utf8'));
const token = devVars.PERSONAL_API_TOKEN || env.PERSONAL_API_TOKEN;
if (!token) fail('No PERSONAL_API_TOKEN in .env or workers/tracker/.dev.vars');
const localDir = join(root, '.local');
mkdirSync(localDir, { recursive: true });
const trackerCard = [
  'PigeonBox email tracking setup',
  '',
  'For recipient opens, deploy a public tracker you own:',
  '  Convex:                 docs/convex-self-hosting.md',
  '  Cloudflare Worker + DB: docs/self-hosting.md',
  '',
  'Personal API token for your deployment:',
  `  ${token}`,
  '',
  'After deployment, enter its public URL and this token in Settings → Email tracking.',
  '',
  'Local development only: npm run tracker at 127.0.0.1:8787 (memory storage by default).',
  'External mail clients cannot reach your computer at this local address.',
  '',
].join('\n');
writeFileSync(join(localDir, 'tracker.txt'), trackerCard);

console.log('\nBuilding the extension…\n');
if (run('npm', ['run', 'build']) !== 0) {
  fail('Build failed. Fix the error above, then run npm run setup again.');
}

const dist = join(root, 'apps', 'extension', 'dist');
if (!existsSync(join(dist, 'manifest.json'))) {
  fail('Build finished, but apps/extension/dist/manifest.json is missing.');
}
const manifest = JSON.parse(readFileSync(join(dist, 'manifest.json'), 'utf8'));
const builtFiles = new Set();
const listBuilt = (dir, prefix = '') => {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const name = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) listBuilt(join(dir, entry.name), name);
    else builtFiles.add(name);
  }
};
listBuilt(dist);
const manifestProblems = validateManifest(manifest, builtFiles);
if (manifestProblems.length) fail(`The built manifest has problems:\n  ${manifestProblems.join('\n  ')}`);

console.log(`
PigeonBox ${manifest.version} is built.

  ${dist}

Load it: chrome://extensions → Developer mode → Load unpacked → pick the folder above.
Then open Gmail. Settings → "How should PigeonBox run?" picks on-device AI, Ollama or your own key.
Categories work with AI off.

Develop:   npm run dev   (then Reload on chrome://extensions)
           or npm run dev:reload, then use "Reload extension" in the popup to rebuild + reload
Check:     npm run verify
Tracking:  deploy Convex or Cloudflare Worker + Supabase to receive recipient opens; see docs/self-hosting.md
           Local development only: npm run tracker at 127.0.0.1:8787 (memory by default)
`);

if (openAfter) {
  const status = run(process.execPath, [join(root, 'scripts', 'open.mjs')]);
  if (status !== 0) process.exit(status);
}
